### ISSUE TITLE
Make eslines smart about moved files

### ISSUE THREAD

**Issue by oandregal** [Automattic/eslines#2]
When you move files around, all errors in those files are going to be reported as errors because eslines does not make any difference between moved files and new ones. 

Reason is: the [differ](https://github.com/Automattic/eslines/blob/master/src/lib/differ.js) takes a git diff as an input and builds the structure of lines modified out of it, but `git diff` does not tell you if a file was simply renamed or not.

**Comment by nb** [comment]
`git diff` usually tells you, unless it was both renamed *and* changed at the same time. Still it may be worth looking at `git diff -M`: https://git-scm.com/docs/git-diff#git-diff--Mltngt
